```{r}
#q1 (used movie_metadata dataset) Generate a report that tracks the various Genere combinations for each type year on year. The result data frame should contain type, Genere_combo, year, avg_rating, min_rating, max_rating, total_run_time_mins

df<-read.csv("movie_metadata.csv")
library(dplyr)
q1<-function(df)
  {
  
   df1=df %>%
    group_by(title_year,genres,color) %>%
    summarize(mean = mean(imdb_score, na.rm = TRUE),
              min = min(imdb_score),sum_of_duration = sum(duration, na.rm = TRUE))
  }
head(q1(df))
```
```{r}
#q2 (used movie_metadata dataset)  Is there a realation between the length of a movie title and the ratings ? Generate a report that captures the trend of the number of letters in movies titles over years. We expect a cross tab between the year of the video release and the quantile that length fall under. The results should contain year, min_length, max_length, num_videos_less_than25Percentile, num_videos_25_50Percentile , num_videos_50_75Percentile, num_videos_greaterthan75Precentile

library(tidyr)
q2<-function(df2)
  {
    df2<-df %>% drop_na()
    df2$title_l=nchar(as.character(df2$movie_title))
    df2$quartile <- ntile(df2$title_l, 4)
    d<-as.data.frame.matrix(table(df2$title_year,df2$quartile))
    
    colnames(d)<-c("num_videos_less_than25Percentile","num_videos_25_50Percentile ","num_videos_50_75Percentile","num_videos_greaterthan75Precentile")
    
    y<-df2%>%group_by(title_year)%>%summarise(min=min(title_l),max=max(title_l))
    y$title_year<-NULL
    return(cbind(y,d))
  }

print(q2(df))
```

```{r}
#q3  In diamonds data set Using the volumne calculated above, create bins that have equal population within them. Generate a report that contains cross tab between bins and cut. Represent the number under each cell as a percentage of total. 

library(descr)
library(imputeTS)
t<-read.csv("diamonds.csv")
q.3<-function(df)
{
  df[is.na(df)]<-0
  df$z[df$z=='None']<-0
  df$volume <- ifelse(df$depth>60,df$x*df$y*(type.convert(df$z)), 8)
  df$quant<-as.numeric(ntile(df$volume, 5))
  y<-crosstab(df$quant,df$cut,plot=FALSE,type="t")
  return(y)
}
print(q.3(t))
```

```{r}
#q4  Generate a report that tracks the Avg. imdb rating quarter on quarter, in the last 10 years, for movies that are top performing. You can take the top 10% grossing movies every quarter. Add the number of top performing movies under each genere in the report as well.

q4<-function(df)
{
  df<-df %>% drop_na()
  df5<-df %>% group_by(title_year)%>%summarise(Avg_Rating=mean(imdb_score))
  
  return(df5)
}

head(q4(df))
```

```{r}
#q5  Bucket the movies into deciles using the duration. Generate the report that tracks various features like nomiations, wins, count, top 3 geners in each decile. 

library(readr)
library(mltools)
u<-read_delim("imdb.csv", delim=',', escape_double=FALSE, escape_backslash=TRUE)
q5<-function(u)
  {
    u$duration[is.na(u$duration)]<-0
    u$dec<-as.numeric(ntile(u$duration, 10))
    df4<-u%>%group_by(dec)%>%summarise(no_of_nomi=sum(nrOfNominations),no_of_wins=sum(nrOfWins))
    df4['count']<-data.frame(table(u$dec))['Freq']
    temp<-u[c(17:45)]
    z<-temp%>%group_by(dec)%>%summarise_all(sum)
    z<-as.data.frame.matrix(t(z))
    names<-row.names(z)
    
    high<-function(x)
      {
        return (names[order(x, decreasing = TRUE)[1:3]])
      }
    
    y1<-as.data.frame.matrix(t(sapply(z,high)))
    colnames(y1)<-c('first','second','third')
    df4['top genres']<-paste(y1$first,',',y1$second,',',y1$third)
    return(df4)
  }
q5(u)
```

