```{r}
library(readr)
library(mltools)
df<-read_delim("imdb.csv", delim=',', escape_double=FALSE, escape_backslash=TRUE)
library(dplyr)
```

```{r}
# 7. Get the imdb rating for fifth movie of dataframe

q7<-function(x)
{
return (df[['imdbRating']][5])
}

q7(5)
```

```{r}
# 8. Return titles of movies with shortest and longest run time


print('minimum duration')
df$title[which.min(df$duration)]
print('maximum duration')
df$title[which.max(df$duration)]
```

```{r}
# 9. Sort the data frame by in the order of when they where released and have higer ratings, Hint : release_date (earliest) and Imdb rating(highest to lowest)
library(tidyr)
q9<-function(df)
  {
    df<-df %>% drop_na(year,imdbRating )
    df1<-df[with(df, order(year,imdbRating)), ]
    return(df1)
  }
head(q9(df))
```

```{r}
# 10. Subset the dataframe with movies having the following prameters. revenue more than 2 million spent less than 1 million duration between 30 mintues to 180 minutes 

q10<-function(df)
  {
    df<-df %>% drop_na(duration )
    return(subset(df,between(duration,1800,10800)))
  }  
head(q10(df))
```

